POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": ""
}

###

POST http://localhost:3333/events/b30a088d-3a7b-49ce-8a29-c3e610adb082/attendees
Content-Type: application/json

{
  "name": "Joao Silva",
  "email": "joao@joao.com"
}

###

GET http://localhost:3333/events/b30a088d-3a7b-49ce-8a29-c3e610adb082

###

GET http://localhost:3333/attendees/9/badge

###

GET http://localhost:3333/attendees/9/check-in

###

GET http://localhost:3333/events/b30a088d-3a7b-49ce-8a29-c3e610adb082/attendees?query=joao